### ISSUE TITLE
Frage: ich komme nicht weiter

### ISSUE THREAD

**Issue by DietmarWiedemann** [joe-the-ark/arks#3]
Hallo zusammen

ich habe von dem Spiel auf Marc Löfflers Pod cast gehört, fand die Simulation einfach nur klasse und wollte es mit meinem Team ausprobieren. 

In der Vorbereitung habe ich auf vier Browser Fenster gespielt. Im Warteraum komme ich allerindings nicht weiter: https://www.arks.ch/waiting-room/

Liegt das an meiner Testsituation? Oder ist es Fehler? Oder habe ich einfach den richtigen Knopf übersehen?

Ich freue mich auf Eure Antwort.

Danke und viele Grüße
Dietmar

(dw@proventa.de)

![Screenshot 2021-05-17 161718](https://user-images.githubusercontent.com/84332305/118503987-67ed1700-b72b-11eb-85bc-c94e27b1450e.png)

**Comment by joe-the-ark** [comment]
Hoi Dietmar, ich lese eben deine Frage auf GitHub – wollen wir kurz zoomen?
mich interessiert dein Issue und ich würde gerne beim troubleshooting helfen…

Cheerio Joachim

**Comment by DietmarWiedemann** [comment]
Klar: 

Dietmar Wiedemann lädt Sie zu einem geplanten Zoom-Meeting ein.

Zoom-Meeting beitreten
https://zoom.us/j/94495753868?pwd=NHdJSzRMeUJiV0FsWHFJSGRmb0hodz09

Meeting-ID: 944 9575 3868
Kenncode: 931109
